"""create two tables

Revision ID: 9d4a9657ccce
Revises: 
Create Date: 2021-03-08 15:17:40.080262

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9d4a9657ccce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "continents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("continent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["continent_id"],
            ["continents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("countries")
    op.drop_table("continents")
    # ### end Alembic commands ###
